---

  # Configure firewall
- name: configure firewall settings
  become: true
  notify:
    - reload_daemon
    - restart_firewalld
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}"
  loop:
    - 8300/tcp
    - 8301/tcp
    - 8302/tcp
    - 8500/tcp
    - 8501/tcp
    - 8502/tcp
    - 21000-21255/tcp
    - 8600/tcp
    - 8301/udp
    - 8302/udp
    - 8600/udp
    - 21000-21255/udp
  when: configure_firewalld
  tags: ["post"]

- name: selinux permissive, logging actions that would be blocked
  become: true
  selinux:
    policy: targeted
    state: permissive
  when: configure_selinux
  tags: ["post"]

# ------------------------------------------------------------------------------

- name: POST | Start and enable {{ application }} unit
  become: true
  notify:
    - reload_daemon
  systemd:
    name: "{{ application }}"
    masked: no
    enabled: yes
    state: started
  tags: ["post"]

# ------------------------------------------------------------------------------

  # Run any handlers
- name: POST | Flush handlers
  meta: flush_handlers
  tags: ["post"]
