---

  # TODO: Include variables specific to your os
- name: include OS variables
  include_vars: default.yml

# ------------------------------------------------------------------------------

  # Run pre-tasks
- name: include dependencies
  include: 010-pre_tasks.yml

# ------------------------------------------------------------------------------

  # Install main application
- name: install {{ application }}
  include: 020-install_main.yml

  # [OPTIONAL] Install dnsmasq dns
- name: install {{ application }}
  include: 025-install_dnsmasq.yml
  when: dnsmasq_enabled

# ------------------------------------------------------------------------------

  # Configure application settings
- name: configure {{ application }}
  include: 030-configure_main.yml

# ------------------------------------------------------------------------------

  # Perform post-install tasks
- name: post-tasks
  include: 040-post_tasks.yml
